data_dir: evaluation/data
data_names: openai_math_splits
data_parallel_size: -1
end: -1
max_tokens_per_call: 8192
model_name_or_path: ./checkpoint
num_test_sample: -1
output_dir: .
overwrite: true
prompt_type: llama-sft
save_outputs: false
seed: 0
shuffle: true
split: test
start: 0
temperature: 0.7
top_p: 1
use_vllm: true